### ISSUE TITLE
Problem with pip install aacgmv2

### ISSUE THREAD

**Issue by billrideout** [aburrell/aacgmv2#14]
When I install aacgmv2 via pip, it is putting the files listed below directly in the site-packages directory, instead of in a subdirectory called aacgmv2. But the aacgmv2 module expects the files to be in that subdirectory, so the import fails unless you manually create that directory under site-packages, and move these files.  This problem has occured on linux systems here at MIT Millstone Hill, and also at Arecibo and at Eiscat.  -Bill Rideout, brideout@mit.edu

_aacgmv2.so
deprecated.py
deprecated.pyc
__init__.py
__init__.pyc
__main__.py
__main__.pyc
wrapper.py
wrapper.pyc

**Comment by aburrell** [comment]
Thank you for the issue report, I'll get on this ASAP.

**Comment by aburrell** [comment]
The new upload to pip addresses this issue.

**Comment by billrideout** [comment]
Thanks for fixing this issue with the aacgmv2 install!  -Bill
