### ISSUE TITLE
Can't pass series of datetimes to accompany series of coordinates

### ISSUE THREAD

**Issue by johncoxon** [aburrell/aacgmv2#21]
When converting coordinates, you can pass a timeseries of coordinates but not the accompanying datetimes to `aacgmv2.convert`. I would have expected to be able to pass a series of datetimes which was the same length as the coordinates to be converted.

I'm not sure how much difference the datetime makes to the conversion when dealing with timescales of seconds, so I'm just using the first datetime in the timeseries for now.

Hope this helps!

```
import numpy as np
import aacgmv2
datetime = np.array([dt.datetime(2017,12,3), dt.datetime(2017,12,3,1)])
latNH, lonNH = np.array([ 45.,  50.]), np.array([ 42.,  84.])
print(aacgmv2.convert(latNH, lonNH, 780, date = datetime[0]))
aacgmv2.convert(latNH, lonNH, 780, date = datetime)
```

The print statement gives `(array([ 44.12680926,  48.63762016]), array([ 115.69978107,  158.0402777 ]))`

And then the following error is thrown:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-9-d3e2673da3f0> in <module>()
----> 1 aacgmv2.convert(latNH, lonNH, 780, date = datetime)

/anaconda2/lib/python2.7/site-packages/aacgmv2/deprecated.pyc in convert(lat, lon, alt, date, a2g, trace, allowtrace, badidea, geocentric)
     73     # convert location
     74     lat_out, lon_out, _ = aacgmv2.convert_latlon_arr(lat, lon, alt, date,
---> 75                                                      code=bit_code)
     76 
     77     return lat_out, lon_out

/anaconda2/lib/python2.7/site-packages/aacgmv2/wrapper.pyc in convert_latlon_arr(in_lat, in_lon, height, dtime, code, igrf_file, coeff_prefix)
    245 
    246     assert isinstance(dtime, dt.datetime), \
--> 247         logging.error('time must be specified as datetime object')
    248 
    249     # Test height

AssertionError: None
```

**Comment by aburrell** [comment]
Hi @johncoxon!

This functionality is a result of the way that the C code for AACGM is structured.  Because you need the time to look up the correct coefficients, it's possible to vectorise with respect to location at a specific time.  However, you need to loop over the different time instances.  So, no vectorisation.

Cheers,
Angeline
