### ISSUE TITLE
How to mute BELOW during the conversion?

### ISSUE THREAD

**Issue by lily771115** [aburrell/aacgmv2#24]
It seems that "BELOW" would be printed out if accessing the forbidden area. The pure python code can't mute this.   I have a batch processing with tqdm, and "BELOW" interrupts and duplicates the progress bar.

```
 62%|███████████████████████████                  | 4962/8036 [39:45<24:37,  2.08it/s]BELOW
BELOW
BELOW
 62%|███████████████████████████                  | 4965/8036 [39:47<24:36,  2.08it/s]BELOW
BELOW
 62%|███████████████████████████                  | 4967/8036 [39:47<24:35,  2.08it/s]BELOW
BELOW
```
I have no idea with how to comment printf of C source code and compile it then pack it into python package. "BELOW" also returns nan and I applied the interpolate to converting nans. Is it rational for the mapping the magnetic coordinate axis on geographic scale figures?

**Comment by aburrell** [comment]
Hi @lily771115 , I need more information before I can help you.  Could you please include:

- Your operating system name and version
- Any details about your local setup that might be helpful in troubleshooting
- Detailed steps to reproduce the bug

**Comment by aburrell** [comment]
Thank you for the information.  I can reproduce your output and see why this is an issue.  As a wrapper, we try not to fuss much with the C code, but introducing a verbosity flag would help you and future users.  I'm going to tag this as an enhancement and talk to Dr. Shepherd about making this change.

There are options for redirecting C-stream output in python, but they vary a lot by python version and operating system.

**Comment by aburrell** [comment]
This is addressed in #26.  If you could test this to make sure it works for you, I would appreciate it.

**Comment by lily771115** [comment]
Hi @aburrell , it works fine for me. Thank you so much. :)

**Comment by aburrell** [comment]
Thank you for your help, and for bringing this to my attention!
