### ISSUE TITLE
Environmental variable warnings printed to stdout

### ISSUE THREAD

**Issue by billrideout** [aburrell/aacgmv2#25]
When running aacgmv2 with a virtual environment, the warnings about environmental variables in __init__.py are printed to stdout.  When using your module, this causes the warnings to leak into my script output.  If you would change all the print() statements in __init__.py to sys.stderr.write() statements, the warnings would go to stderr and would solve my issue.  For now, I simply edited the file myself, so this is not a critical issue in my case. -Bill

**Comment by aburrell** [comment]
Thank you for the feedback, I'll make this change.

**Comment by aburrell** [comment]
Addressed in #27.  Ff you have time to test this, I would appreciate another set of eyes.  If not, I'll merge it in this week.
