### ISSUE TITLE
I didn't notice that convert was deprecated

### ISSUE THREAD

**Issue by johncoxon** [aburrell/aacgmv2#31]
I have been using `aacgmv2.convert` because, when I first imported the `aacgmv2` module, I simply typed `aacgmv2.` and then hit tab in my Jupyter notebook, and chose `convert` because it looks like the most sensible of the methods that present themselves when one does that. I've just noticed that the `convert` routine is in `deprecated.py`, and I should probably have been using something like `get_aacgm_coord_arr`. 

I appreciate the above is entirely my fault for diving in and starting hacking without RTM, but I imagine that I'm not the only one who tends to learn Python modules through usage instead of through documentation. To that end, could `convert` print something, or maybe throw a `FutureWarning`, so that it's more obvious to an end user that this routine is deprecated and other routines are better choices?

**Comment by aburrell** [comment]
This is a great point John.  I kept convert as one of the available routines to avoid breaking anyone's code, but it would be better to throw up a deprecation warning and eventually remove it in a future major release.

**Comment by aburrell** [comment]
I'll merge this into master in about a month.  I'd like make a few more stylistic improvements before pushing out another minor release.
