### ISSUE TITLE
Question: logbook dependency

### ISSUE THREAD

**Issue by asreimer** [aburrell/aacgmv2#33]
Quick question, why is the `logbook` used instead of `logging`? I didn't dig through the codebase much, but it doesn't look like the features of logbook are being used in a way that necessitates using it?

**Comment by aburrell** [comment]
At some point logging was deprecated and logbook was the replacement.  I made the change, but then started using warnings more and kept logging for more informational output.

**Comment by aburrell** [comment]
If you have a compelling reason to change things, I have a deprecation warning that needs to be propagated from the develop to the master branch and am willing to do some additional stylistic fine-tuning.

**Comment by asreimer** [comment]
`logging` was deprecated? I can't find any information about this with a Google search. It's included in python 3.7 even: https://docs.python.org/3/library/logging.html

Mostly just curious. The most compelling reason to use `logging` instead of `logbook` is that users don't need to install another dependency if `logging` is used, especially if none of the `logbook` functionality is being used.

**Comment by aburrell** [comment]
I wish I could point you somewhere, but it was a few years ago and I don't remember.  Clearly it didn't happen.

Removing dependencies is a good enough reason for me.  I will put it on the to-do list.

**Comment by asreimer** [comment]
No worries. I am mostly curious because we use logging a lot and if it were deprecated I would want to be moving away from it to something else!

**Comment by aburrell** [comment]
Addressed in new branch, will be out in the next version.
