### ISSUE TITLE
nan handling is not what I would expect

### ISSUE THREAD

**Issue by johncoxon** [aburrell/aacgmv2#34]
**Describe the bug**
The library appears to introduce spurious data duplicates when an input contains `nan`.

**To Reproduce**
Set the following variables:
```
latitude = np.array([44.757, np.nan, 46])
longitude = np.array([286.893, np.nan, 290])
height = np.array([100, np.nan, 100])
date = dt.datetime(2001,1,1,2,26)
```
Then, run the following line of code:
```
aacgm.get_aacgm_coord_arr(latitude, longitude, height, date)
```
which results in this output:
```
array([ 55.10077765, -55.10077765,  55.86473325]),
array([4.46850515, 4.46850515, 8.97687841]),
array([21.72454211, 21.72454211, 22.02510033])
```
**Expected behavior**
I would expect the middle of each of the output arrays to be `nan`, or for the code to throw some exception or error.

**Desktop:**
- OS: macOS 10.14.3
- Version: 2.4.2

**Comment by aburrell** [comment]
This is odd.  I can't reproduce your error.  For entries with NaN, I get NaNs returned.

**Comment by johncoxon** [comment]
That is strange! I tried it in IPython and Python and get the behaviour in both -- I'm using `aacgmv2` version `2.4.2`, is that not the latest perhaps?

**Comment by aburrell** [comment]
I was using the develop branch.  Would you mind giving that a try?

**Comment by johncoxon** [comment]
I switched to the develop branch and ran `python setup.py install` and then ran the code above and I got the same result… Do I need to try to run the install forcing it to recompile the C code?

**Comment by aburrell** [comment]
No, it should work.  Ok... I'll take another look at this after I finish issue #35

**Comment by johncoxon** [comment]
Doing `python setup.py install` from the `develop` branch of the Git repo (after deleting any path matching `aacgmv2.+` in `site-packages`) looks like this:

```
In [1]: import aacgmv2 as aacgm

In [2]: latitude = np.array([44.757, np.nan, 46])
   ...: longitude = np.array([286.893, np.nan, 290])
   ...: height = np.array([100, np.nan, 100])
   ...: date = dt.datetime(2001,1,1,2,26)
   ...: 
   ...: 

In [3]: aacgm.get_aacgm_coord_arr(latitude, longitude, height, date)
/anaconda2/envs/python3/lib/python3.6/site-packages/numpy/lib/function_base.py:2831: RuntimeWarning: invalid value encountered in ? (vectorized)
  outputs = ufunc(*inputs)
Out[3]: 
(array([55.09932767,         nan, 55.86362559]),
 array([4.4669493 ,        nan, 8.97511275]),
 array([21.72443839,         nan, 22.02498262]))
```

I'll stick with the current installation for now, since this is exactly what I need. Thanks for your help!
