### ISSUE TITLE
Total Python hang with certain values passed to get_aacgm_coord_arr

### ISSUE THREAD

**Issue by johncoxon** [aburrell/aacgmv2#35]
**Describe the bug**
In some circumstances, `get_aacgm_coord_arr` completely hangs.

**To Reproduce**
Run `aacgm.get_aacgm_coord_arr(44.757, 286.893, 6371000000.2, dt.datetime(2001,1,1,2,26))` and Python completely hangs.

I initially thought this was because `height` was set too high, but `aacgm.get_aacgm_coord_arr(0., 180., 1000000000000000000., dt.datetime(2001,1,1,2,26))` doesn't hang, and I don't know why.

**Expected behavior**
I would expect it not to hang (I think I'd expect some sort of exception to be thrown since the height value is so clearly too high to be a valid input).

**Desktop (please complete the following information):**
- OS: macOS 10.14.3
- Version: 2.4.2

**Comment by aburrell** [comment]
It looks like it's probably hanging because it expects an array or list but is getting a float.  No idea why the other one is working.  I'm adding a fix for this.

**Comment by aburrell** [comment]
Ok, I cleaned up the array/float handling (it was there but could handled better) so that wasn't the issue.  It looks like there might be a problem in the C code.

**Comment by johncoxon** [comment]
Is it worth having `get_aacgm_coord_arr` throw a `ValueError` before the call to the C code in cases where the height is nonsensical, to prevent the hang? That seems like the simplest way to prevent this happening in other people's code?

**Comment by aburrell** [comment]
Ok, I found that the case you found caused the tracing routine to diverge.  I added an additional exit condition, but want to clear it with Simon since it's in the C code.

**Comment by aburrell** [comment]
@johncoxon limiting the height is also a good thing to do, but I highly support having enough exit conditions to prevent corner cases from causing infinite loops :-P

**Comment by aburrell** [comment]
So the infinite loop fix I did basically ends up causing all tracing to fail.  Instead, I'm looking at establishing an upper limit on a sensible altitude.  Any guidelines/ideas you have would be helpful @johncoxon.

**Comment by aburrell** [comment]
@johncoxon do you mind testing the pull request: #36 ? There are three versions of python/windows that are failing on appveyor but it passes for linux machines on travis.  Would be good to have your eyes on it to ensure the warning message is informative and useful.

**Comment by johncoxon** [comment]
I'm happy to test it! I'm currently working on a proposal but I've added it to my to-do list…

**Comment by aburrell** [comment]
Great!  It's ready to merge now.  Once you test it I'll do another release to master.

**Comment by johncoxon** [comment]
I pulled from the `develop` branch this morning and installed `aacgmv2` to bring myself to v2.5.2 and tested it out:
```
aacgm.get_aacgm_coord_arr(44.757, 286.893, 6371000000.2, dt.datetime(2001,1,1,2,26))
for a single location, consider using convert_latlon or get_aacgm_coord
these coordinates are not intended for the magnetosphere! You must indicate that you know this is a bad idea.  If you continue, it is possible that the code will hang.
Out[10]: (array([nan]), array([nan]), array([nan]))
```

Seems to work great!
