### ISSUE TITLE
Problem with warning even when env variables not changing

### ISSUE THREAD

**Issue by billrideout** [aburrell/aacgmv2#37]
I was wondering if we could change the __init__.py method to not output a warning when the two env variables are being set to what they already were.  In the version below the warning only occurs if they are being set to a different value. In the present version there is a warning even if the value is not changing. I get this warning when python calls a subprocess that also imports aacgmv2. Here are the lines with this change:

# If not defined, or defined but different, set the IGRF and AACGM environment variables
reset_warn = False
if 'IGRF_COEFFS' in _os.environ.keys():
    if not _os.environ['IGRF_COEFFS'] == IGRF_COEFFS:
        print("resetting environment variable IGRF_COEFFS in python script")
        reset_warn = True
_os.environ['IGRF_COEFFS'] = IGRF_COEFFS

if 'AACGM_v2_DAT_PREFIX' in _os.environ.keys():
    if not _os.environ['AACGM_v2_DAT_PREFIX'] == AACGM_v2_DAT_PREFIX:
        print("resetting environment variable AACGM_v2_DAT_PREFIX in python script")
        reset_warn = True
_os.environ['AACGM_v2_DAT_PREFIX'] = AACGM_v2_DAT_PREFIX

**Comment by aburrell** [comment]
This is a good idea, thanks for supplying the code lines.  I'll be sure to make this change before the next version release.

**Comment by aburrell** [comment]
Ok, made the changes.  Would you mind testing #38 to make sure the behaviour works well for you on your system?

**Comment by billrideout** [comment]
Angeline,

That worked well on my system.  Here's what I got before the update:


(gps3) Bills-MacBook-Pro:~ brideout$ export AACGM_v2_DAT_PREFIX=/anaconda3/envs/gps3/lib/python3.7/site-packages/aacgmv2/aacgm_coeffs/aacgm_coeffs-12-
(gps3) Bills-MacBook-Pro:~ brideout$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['AACGM_v2_DAT_PREFIX']
'/anaconda3/envs/gps3/lib/python3.7/site-packages/aacgmv2/aacgm_coeffs/aacgm_coeffs-12-'
>>> import aacgmv2
resetting environment variable AACGM_v2_DAT_PREFIX in python script
non-default coefficient files may be specified by running aacgmv2.wrapper.set_coeff_path before any other functions
>>> os.environ['AACGM_v2_DAT_PREFIX']
'/anaconda3/envs/gps3/lib/python3.7/site-packages/aacgmv2/aacgm_coeffs/aacgm_coeffs-12-'

After I installed the env_warn branch I got no warning:

(gps3) Bills-MacBook-Pro:~ brideout$ export AACGM_v2_DAT_PREFIX=/anaconda3/envs/gps3/lib/python3.7/site-packages/aacgmv2-2.5.1-py3.7-macosx-10.7-x86_64.egg/aacgmv2/aacgm_coeffs/aacgm_coeffs-12-
(gps3) Bills-MacBook-Pro:~ brideout$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['AACGM_v2_DAT_PREFIX']
'/anaconda3/envs/gps3/lib/python3.7/site-packages/aacgmv2-2.5.1-py3.7-macosx-10.7-x86_64.egg/aacgmv2/aacgm_coeffs/aacgm_coeffs-12-'
>>> import aacgmv2
>>> 

Thanks - Bill

**Comment by aburrell** [comment]
Thank you!
