### ISSUE TITLE
Copyright and License disclaimer 

### ISSUE THREAD

**Issue by mts299** [aburrell/aacgmv2#39]
In the future, you may want to add a copyright line at the top with a disclaimer indicating where the license file and maybe which license you are using as this is a requirement of the MIT license. 
For example:
```python
# Copyright (C) 2019 NRL 
# Author: Angeline Burrell
# Disclaimer: This code is under the MIT license found at the root in the LICENSE file
``` 
This will help users know who to contact about the code or what privileges they have based on the license. 

As a reminder LICENSES trump copyrights privileges, so open-source licenses use copyrights as a line of credit to the author.

**Comment by aburrell** [comment]
Did this one a bit too early in the morning and made the commit straight to develop.
