### ISSUE TITLE
nans taking over the output of get_aacgm_coord_arr

### ISSUE THREAD

**Issue by johncoxon** [aburrell/aacgmv2#42]
**Describe the bug**
Sometimes, `nan` takes over the output of `get_aacgm_coord_arr`.

**To Reproduce**
Run the following code:
```
import aacgmv2 as aacgm
lat = [25.69817439, 19.81656206]
lon = [19.184186, 19.11999446]
alt = [465.28404149, 466.37134689]
print(aacgm.get_aacgm_coord_arr(lat[0], lon[0], alt[0], dt.datetime(2014,12,7,16,17)))
print(aacgm.get_aacgm_coord_arr(lat[1], lon[1], alt[1], dt.datetime(2014,12,7,16,17)))
print(aacgm.get_aacgm_coord_arr(lat, lon, alt, dt.datetime(2014,12,7,16,17)))
```
and you get:
```
(array([21.06023285]), array([91.8062328]), array([17.81449611]))
(array([nan]), array([nan]), array([nan]))
(array([nan, nan]), array([nan, nan]), array([nan, nan]))
```

Running `get_aacgm_coord_arr` with `method=allowtrace` eliminates all the `nan` values in the above example, implying that setting `allowtrace` as the default `method` might help, but the following code also exhibits the same bug:
```
lat = [25.69817439, 17.14050096]
lon = [19.184186, -4.46442997]
alt = [465.28404149, 466.79848959]
method = 'geocentric|allowtrace'
print(aacgm.get_aacgm_coord_arr(lat[0], lon[0], alt[0], dt.datetime(2014,12,7,16,17), method=method))
print(aacgm.get_aacgm_coord_arr(lat[1], lon[1], alt[1], dt.datetime(2014,12,7,16,17), method=method))
print(aacgm.get_aacgm_coord_arr(lat, lon, alt, dt.datetime(2014,12,7,16,17), method=method))
```
This code results in the following:
```
(array([21.16991252]), array([91.79687939]), array([17.81387255]))
(array([nan]), array([nan]), array([nan]))
(array([nan, nan]), array([nan, nan]), array([nan, nan]))
```

**Expected behavior**
I would expect the final print statement in the first example to print `(array([21.06023285, nan]), array([91.8062328, nan]), array([17.81449611, nan]))` and in the second example to print `(array([21.16991252, nan]), array([91.79687939, nan]), array([17.81387255, nan]))
`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Version 2.5.2 (commit `e4961ed`)

**Comment by aburrell** [comment]
@johncoxon could you test #43 ?  It should be good to go now.

**Comment by johncoxon** [comment]
Hi Angeline, I've checked out `origin/NaN_bug_get_aacgm_coord` and `python setup.py install`'d it, and I still get the behaviour I've reported above, I'm afraid.

**Comment by johncoxon** [comment]
The proposed bug fix actually breaks some existing behaviours, as now `get_aacgm_coord_arr` returns lists rather than arrays which causes some of my existing code to need modification to cope with that; I've reverted back to `master` for now so I don't have to write workarounds into my code.

**Comment by aburrell** [comment]
Hi @johncoxon , can you show me the results you got after installing it?  I can't move forward without being able to reproduce your failure.

**Comment by aburrell** [comment]
> The proposed bug fix actually breaks some existing behaviours, as now get_aacgm_coord_arr returns lists rather than arrays which causes some of my existing code to need modification to cope with that

Yeah, in order to do this in C, the output has to be a list.  The python wrappers could cast the output as numpy arrays, and from your feedback I am guessing that would be a desired behaviour?

**Comment by johncoxon** [comment]
Sorry, I should have said--the results I get after installing are the same as in the initial bug report:
```
([21.169912518324892], [91.79687938812465], [17.81387254816658])
(array([nan]), array([nan]), [nan])
(array([nan, nan]), array([nan, nan]), [nan, nan])
```
I do now get two errors which say `C Error encountered: <built-in function convert_arr> returned a result with an error set`, though, if that helps? I'm confident that I've installed the changed version because I've had to wrap the lists in `np.array()`s for now.

**Comment by johncoxon** [comment]
```
>>> import aacgmv2 as aacgm
>>> lat = [25.69817439, 17.14050096]
>>> lon = [19.184186, -4.46442997]
>>> alt = [465.28404149, 466.79848959]
>>> method = 'ALLOWTRACE|GEOCENTRIC'
>>> print(aacgm.get_aacgm_coord_arr(lat[0], lon[0], alt[0], dt.datetime(2014,12,7,16,17), method=method))
(array([21.16991252]), array([91.79687939]), array([17.81387255]))
>>> print(aacgm.get_aacgm_coord_arr(lat[1], lon[1], alt[1], dt.datetime(2014,12,7,16,17), method=method))
(array([nan]), array([nan]), array([nan]))
>>> print(aacgm.get_aacgm_coord_arr(lat, lon, alt, dt.datetime(2014,12,7,16,17), method=method))
(array([21.16991252,         nan]), array([91.79687939,         nan]), array([17.81387255,         nan]))
```
I pulled the latest changes on `NaN_bug_get_aacgm_coord` and this is the result, so I think this bug is addressed in that branch. Should be good to merge into the main repo!

**Comment by aburrell** [comment]
Ok, I merged into develop and will prepare the version bump to major next week.
