### ISSUE TITLE
code to method_code parameter change not documented

### ISSUE THREAD

**Issue by TeriForey** [aburrell/aacgmv2#44]
**Describe the bug**
In the minor change from 2.5.1 to 2.5.2 you've changed the input parameter name in `convert_latlon` from 'code' to 'method_code'. This isn't in the documentation, nor is it in the changelog. It meant that the package I've developing which uses this function no longer works without me either updating it, or fixing the version of aacgmv2 to 2.5.1.

**To Reproduce**
`pip install "aacgmv2==2.5.2"`
```
import aacgmv2
aacgmv2.convert_latlon_arr([90, -90], 0, 0, dtime, code="A2G")
```
(Note this is the example from your docs. Will now return a Type Error convert_latlon_arr() got an unexpected keyword argument 'code')

**Expected behavior**

**Screenshots or Figures**
If applicable, add visual aids to help explain your problem.

**Desktop (please complete the following information):**
- Any details about your local setup that might be helpful in troubleshooting

**Additional context**

Will the parameter name stay as 'method_code' in future versions?

**Comment by aburrell** [comment]
Thanks for finding this.  Looking at the code, I remember now that this was changed in response to a request for having more descriptive variable names.  I can probably get to this next week.  Here's what I plan to do:

1) update the documentation
2) update the changelog
3) add an option to use `code`, but its use will trigger a deprecation warning that the user should switch to `method_code`
4) schedule the removal of `code` for the release of version 2.5.4

I was getting ready to release version 2.5.3, but will get this in first.

**Comment by aburrell** [comment]
@TeriForey, would you be able to run the test in pull request #45 to ensure that the behavior fixes the `code` bug you found?

**Comment by TeriForey** [comment]
Thanks @aburrell that looks to have fixed the bug. The test works and I can see the deprecation warning when using `code`.

**Comment by aburrell** [comment]
@TeriForey I will let you know when the new version with this change comes out (realistically, before Christmas).  In the meantime, I am merging this fix into develop.
