### ISSUE TITLE
Keep utility functions currently marked as deprecated

### ISSUE THREAD

**Issue by asreimer** [aburrell/aacgmv2#49]
Currently, there are 3 functions in `aacgmv2.deprecated`:
* `gc2gd_lat`
* `igrf_dipole_axis`
* `subsol`

Arguably, `gc2gd_lat` could be deprecated since this kind of function is better served via something like [pymap3d](https://github.com/scivision/pymap3d), however, the other 2 functions are extremely useful to have when using aacgm and weimer.

In order to properly drive [weimer](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2004JA010884), one needs the dipole tilt axis, as defined in [Laundal and Richmond 2016](https://link.springer.com/article/10.1007/s11214-016-0275-y), equation 15. This requires both the IGRF dipole axis and the subsolar point.

Since weimer uses aacgm coordinates and it needs to be driven with the dipole tilt axis, I recommend that `igrf_dipole_axis` and `subsol` are removed from deprecation plans and instead moved into something like a `utils` sub module or something.

Thoughts?

**Comment by aburrell** [comment]
Thanks for the input @asreimer.  I wasn't sure if anyone was using them, and wanted to get rid of anything unnecessary.  Since they are useful for something directly related to AACGMV2, I agree that it makes sense to keep `subsol` and `igrf_dipole_axis`.  `utils` seems sensible, though it may be simpler to just move them to the main function level.

**Comment by st-bender** [comment]
I would also have appreciated if `convert` would not have been removed.

**Comment by aburrell** [comment]
@st-bender I appreciate your feedback.  However, the functionality of convert exists in other, more inclusive routines and so is not in the queue to be added back in.

**Comment by st-bender** [comment]
I disagree, the current interface does not come close to the simplicity and ease of use that `convert()` once provided. What was wrong with it?

**Comment by st-bender** [comment]
I disagree, the current interface does not come close to the simplicity and ease of use that `convert()` once provided. What was wrong with it?

**Comment by aburrell** [comment]
@asreimer would you mind reviewing the PR #57 ?
