### ISSUE TITLE
Units and conventions needed in documentation

### ISSUE THREAD

**Issue by DerekMcKay** [aburrell/aacgmv2#5]
In the documentation, it would be useful to include the units and conventions. For example, is the longitude in degree or radians? Is east positive, or is west positive? Is the altitude in feet, metres or kilometres? What is the reference level for the altitude; the spheroid or an average Earth radius or what?

Yes, in principle one can open up the code and take a look, but it would save a lot of hassle (and confusion) to have it in the documentation where the arguments are described.

Ref: https://aacgmv2.readthedocs.io/en/stable/reference/aacgmv2.html

**Comment by cmeeren** [comment]
Sure, that makes sense. Could you make a pull request? As far as I can remember (I haven't used this in a year and won't ever use this again; I've left academia), it's degrees (east positive) and km, does that sound right? I don't remember what the reference level is.

**Comment by klaundal** [comment]
I can confirm that it is degrees, east positive, and km. I agree that it should be in the documentation.

The reference height is more complicated, and I think it would be best to just reference Richmond's 1995 paper for this, or the 2016 Laundal & Richmond review paper. The reference height is relevant only for the modified apex latitude, which is defined like this: Trace from the point in question to the apex of the magnetic field line using the IGRF. The modified apex latitude is the latitude of the intersection of a dipole field line with radius RE + apex height with a sphere of radius RE + reference height. Basically it is the same as CGM, only CGM always uses the intersection with RE + zero.
