### ISSUE TITLE
Convert LatLon returning NaN

### ISSUE THREAD

**Issue by TeriForey** [aburrell/aacgmv2#50]
**Describe the bug**
I'm trying to convert a series of glat,glon coordinates into mlat,mlon for a bunch of different dates. Depending on the date, I either return value or an array of NaN. 

For example, converting the same 5 coordinates at different dates produces:
```
2013-09-01 00:00:00
[[18.82371153  0.98749918  2.48735885  5.84156392  8.18149188]]
2013-10-01 00:00:00
[[18.82657586  0.77711836  2.41151422  5.80920526  8.1584157 ]]
2013-11-01 00:00:00
[[18.82953417  0.46936     2.33055034  5.77557778  8.13450176]]
2013-12-01 00:00:00
[[nan nan nan nan nan]]
2014-01-01 00:00:00
[[nan nan nan nan nan]]
```

**To Reproduce**

To reproduce, convert the following at different dates:
```
glat = [25.0, 25.0, 25.10351562500003, 25.63629150390625, 26.254516601562557]
glon = [34.82256126193528, -14.871570546036931, -14.8245849609375, -14.800903320312472, -14.439880371093778]

date_working = datetime(year=2013, month=11, day=1, hour=0, minute=0)
date_failing = datetime(year=2013, month=12, day=1, hour=0, minute=0)

aacgmv2.convert_latlon_arr(glat, glon, 100, date_working, code='G2A')
aacgmv2.convert_latlon_arr(glat, glon, 100, date_failing, code='G2A')
```

**Expected behavior**
I would expect it to return the values. If one of the positions fails it should have a single NaN value but not the whole array. Also, it should return a warning describing why it has failed.

**Desktop (please complete the following information):**
 - OS: osx
 - Version: 2.5.1

**Comment by aburrell** [comment]
This issue was identified previously in issue #42 and fixed in the 2.6.0 release.
