### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by vascoamaralgrilo** [aburrell/aacgmv2#51]
Good afternoon,

I was trying to install aacgmv2 with pip as suggested in the quick start, but I get an installation error. The output is presented below. 

Any help would be very appreciated.

Kind regards,

Vasco Grilo

(venv) C:\Users\vasco\Documents\Education\Trabalhos\University 5th year - 2019 2020\2nd semester\Msc thesis\calcs>pip install aacgmv2
Collecting aacgmv2
  Using cached https://files.pythonhosted.org/packages/83/7a/4556faee3ce5d1fa377ef25d869e8dd6952f0cfd06228ec515ca0293f709/aacgmv2-2.6.0.tar.gz
Requirement already satisfied: numpy in c:\users\vasco\documents\education\trabalhos\university 5th year - 2019 2020\2nd semester\msc thesis\calcs\venv\lib\site-packages (from aac
gmv2) (1.18.1)
Installing collected packages: aacgmv2
  Running setup.py install for aacgmv2 ... error
    Complete output from command "C:\Users\vasco\Documents\Education\Trabalhos\University 5th year - 2019 2020\2nd semester\Msc thesis\calcs\venv\Scripts\python.exe" -u -c "import
 setuptools, tokenize;__file__='C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-kwyremmt\\aacgmv2\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f
.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-j8wiyojo\install-recor
d.txt --single-version-externally-managed --compile --install-headers "C:\Users\vasco\Documents\Education\Trabalhos\University 5th year - 2019 2020\2nd semester\Msc thesis\calcs\v
env\include\site\python3.6\aacgmv2":
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\aacgmv2
    copying aacgmv2\deprecated.py -> build\lib.win-amd64-3.6\aacgmv2
    copying aacgmv2\wrapper.py -> build\lib.win-amd64-3.6\aacgmv2
    copying aacgmv2\__init__.py -> build\lib.win-amd64-3.6\aacgmv2
    copying aacgmv2\__main__.py -> build\lib.win-amd64-3.6\aacgmv2
    running egg_info
    writing aacgmv2.egg-info\PKG-INFO
    writing dependency_links to aacgmv2.egg-info\dependency_links.txt
    writing entry points to aacgmv2.egg-info\entry_points.txt
    writing requirements to aacgmv2.egg-info\requires.txt
    writing top-level names to aacgmv2.egg-info\top_level.txt
    reading manifest file 'aacgmv2.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '.isort.cfg'
    warning: no files found matching '.pylintrc'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    warning: no previously-included files matching '*.dSYM' found anywhere in distribution
    warning: no previously-included files matching '.pytest_cache' found anywhere in distribution
    writing manifest file 'aacgmv2.egg-info\SOURCES.txt'
    copying aacgmv2\aacgmv2module.c -> build\lib.win-amd64-3.6\aacgmv2
    copying aacgmv2\igrf13coeffs.txt -> build\lib.win-amd64-3.6\aacgmv2
    copying aacgmv2\magmodel_1590-2020.txt -> build\lib.win-amd64-3.6\aacgmv2
    creating build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1590.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1595.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1600.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1605.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1610.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1615.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1620.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1625.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1630.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1635.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1640.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1645.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1650.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1655.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1660.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1665.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1670.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1675.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1680.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1685.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1690.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1695.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1700.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1705.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1710.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1715.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1720.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1725.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1730.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1735.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1740.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1745.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1750.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1755.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1760.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1765.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1770.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1775.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1780.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1785.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1790.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1795.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1800.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1805.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1810.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1815.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1820.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1825.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1830.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1835.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1840.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1845.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1850.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1855.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1860.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1865.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1870.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1875.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1880.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1885.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1890.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1895.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1900.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1905.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1910.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1915.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1920.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1925.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1930.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1935.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1940.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1945.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1950.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1955.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1960.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1965.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1970.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1975.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1980.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1985.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1990.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-1995.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-2000.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-2005.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-2010.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-2015.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-2020.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    copying aacgmv2\aacgm_coeffs\aacgm_coeffs-13-2025.asc -> build\lib.win-amd64-3.6\aacgmv2\aacgm_coeffs
    creating build\lib.win-amd64-3.6\aacgmv2\aacgmv2.egg-info
    copying aacgmv2\aacgmv2.egg-info\SOURCES.txt -> build\lib.win-amd64-3.6\aacgmv2\aacgmv2.egg-info
    copying aacgmv2\aacgmv2.egg-info\dependency_links.txt -> build\lib.win-amd64-3.6\aacgmv2\aacgmv2.egg-info
    copying aacgmv2\aacgmv2.egg-info\entry_points.txt -> build\lib.win-amd64-3.6\aacgmv2\aacgmv2.egg-info
    copying aacgmv2\aacgmv2.egg-info\requires.txt -> build\lib.win-amd64-3.6\aacgmv2\aacgmv2.egg-info
    copying aacgmv2\aacgmv2.egg-info\top_level.txt -> build\lib.win-amd64-3.6\aacgmv2\aacgmv2.egg-info
    creating build\lib.win-amd64-3.6\aacgmv2\tests
    copying aacgmv2\tests\test_c_aacgmv2.py -> build\lib.win-amd64-3.6\aacgmv2\tests
    copying aacgmv2\tests\test_cmd_aacgmv2.py -> build\lib.win-amd64-3.6\aacgmv2\tests
    copying aacgmv2\tests\test_dep_aacgmv2.py -> build\lib.win-amd64-3.6\aacgmv2\tests
    copying aacgmv2\tests\test_environ_aacgmv2.py -> build\lib.win-amd64-3.6\aacgmv2\tests
    copying aacgmv2\tests\test_py_aacgmv2.py -> build\lib.win-amd64-3.6\aacgmv2\tests
    copying aacgmv2\tests\test_struct_aacgmv2.py -> build\lib.win-amd64-3.6\aacgmv2\tests
    creating build\lib.win-amd64-3.6\aacgmv2\tests\test_data
    copying aacgmv2\tests\test_data\test_convert.txt -> build\lib.win-amd64-3.6\aacgmv2\tests\test_data
    copying aacgmv2\tests\test_data\test_convert_mlt.txt -> build\lib.win-amd64-3.6\aacgmv2\tests\test_data
    copying aacgmv2\tests\test_data\test_convert_mlt_single_line.txt -> build\lib.win-amd64-3.6\aacgmv2\tests\test_data
    copying aacgmv2\tests\test_data\test_convert_single_line.txt -> build\lib.win-amd64-3.6\aacgmv2\tests\test_data
    running build_ext
    building 'aacgmv2._aacgmv2' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\aacgmv2
    creating build\temp.win-amd64-3.6\Release\c_aacgmv2
    creating build\temp.win-amd64-3.6\Release\c_aacgmv2\src
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic_aacgmv2/include "-IC:\Users\vasco\Documents\Education\Traba
lhos\University 5th year - 2019 2020\2nd semester\Msc thesis\calcs\venv\include" -IC:\Users\vasco\AppData\Local\Programs\Python\Python36\include -IC:\Users\vasco\AppData\Local\Pro
grams\Python\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Pr
ogram Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcaacgmv2/aacgmv2module.c /Fobuild\temp.win-amd64-3.6\Release\aacgmv2/aacgmv2module.obj
    aacgmv2module.c
    c:\users\vasco\appdata\local\programs\python\python36\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command ""C:\Users\vasco\Documents\Education\Trabalhos\University 5th year - 2019 2020\2nd semester\Msc thesis\calcs\venv\Scripts\python.exe" -u -c "import setuptools, tokenize;__
file__='C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-kwyremmt\\aacgmv2\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-j8wiyojo\install-record.txt --single-version-e
xternally-managed --compile --install-headers "C:\Users\vasco\Documents\Education\Trabalhos\University 5th year - 2019 2020\2nd semester\Msc thesis\calcs\venv\include\site\python3
.6\aacgmv2"" failed with error code 1 in C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-kwyremmt\aacgmv2\

**Comment by aburrell** [comment]
Hi @vascoamaralgrilo, it looks like this is an issue with the Windows 10 operating system.  There are some fixes presented here: https://github.com/Azure/azure-iot-sdk-python/issues/82.  Can you try them out and let me know if they work?

**Comment by vascoamaralgrilo** [comment]
Thank you very much, installing windows 10 SDK as suggested on one of the links you provided solved the issue!Kind regards,Vasco Sent from Mail for Windows 10 From: Angeline BurrellSent: 30 March 2020 17:56To: aburrell/aacgmv2Cc: vascoamaralgrilo; MentionSubject: Re: [aburrell/aacgmv2] Installation error (#51) Hi @vascoamaralgrilo, it looks like this is an issue with the Windows 10 operating system. There are some fixes presented here: Azure/azure-iot-sdk-python#82. Can you try them out and let me know if they work?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aburrell** [comment]
> -->Thank you very much, installing windows 10 SDK as suggested on one of the links you provided solved the issue!Kind regards,Vasco

I'm glad that worked!
