### ISSUE TITLE
Remove Python 2 support

### ISSUE THREAD

**Issue by aburrell** [aburrell/aacgmv2#59]
**Is your feature request related to a problem? Please describe.**
Support for python 2 ended at the beginning of 2020.

**Describe the solution you'd like**
In the next release, remove support for python 2

**Describe alternatives you've considered**
Continuing to support python 2, but this becomes increasingly difficult as upstream packages drop their support.

**Comment by hugovk** [comment]
Please see PR https://github.com/aburrell/aacgmv2/pull/61.
