### ISSUE TITLE
More use examples

### ISSUE THREAD

**Issue by aburrell** [aburrell/aacgmv2#70]
**Is your feature request related to a problem? Please describe.**
Some people have trouble figuring out how to use the functions for their own purposes

**Describe the solution you'd like**
More use examples in the documentation

**Describe alternatives you've considered**
Answering questions as they come up

**Reminders**
This is a volunteer-driven project.  Code contributions are welcome, as is help
testing new code.

**Comment by hlmxlj2018** [comment]
Sorry, excuse me. I want to know if, after altitude correction of orbits using AACGM module, the input is satellite (geographic latitude, geographic longitude and altitude) and the output is (magnetic latitude, magnetic longitude, magnetic place). Is the corresponding output altitude location the default surface height or something else?

**Comment by hlmxlj2018** [comment]
Sorry, excuse me. Using the AACGM module for altitude correction of orbits, satellites are input (geographic latitude, geographic longitude and altitude) and outputs (magnetic latitude, magnetic longitude, magnetic place). I want to know if the corresponding output altitude location is the default surface height or something else?

**Comment by aburrell** [comment]
It depends on the flags you're using.  As stated in the docs, the returned height is either geocentric radial distance or height above the surface of the Earth (https://aacgmv2.readthedocs.io/en/latest/reference/aacgmv2.html). Can you give me a code example?  For best formatting, be sure to flank the commands between three accent marks ('`').

**Comment by hlmxlj2018** [comment]
For example: '''aacgmv2.wrapper.get_aacgm_coord_arr(glat, glon, height, dtime, method='TRACE')'''.  In this case, in_Lat, in_lon, height, and dtime, the four input values are the satellite's current latitude, longitude, altitude, and time.  The output result is' MLAT ',' MLON ',' MLT ', there is no height information in the result, but there is height information in the input data, I want to know which plane the output result is projected to, is it on the earth surface by default?

**Comment by aburrell** [comment]
It's at the height you input (`height`). That's why no height information is output, it is used in the calculation and not altered.

**Comment by hlmxlj2018** [comment]
If "`height" refers to the output altitude, how can I determine the current position of the satellite only by( "glat" , "glon" )when I input it?In the same geographic longitude and latitude, but at different altitudes, the corresponding geomagnetic field lines are also different. How can we correct them？
So what I don't understand is that if the "height" here refers to the given height after output, isn't the input position information enough to track along the geomagnetic line? Rely only on latitude and longitude.

**Comment by hlmxlj2018** [comment]
Isn't the function of AACGM to track a satellite position to another low altitude plane according to the geomagnetic field line

**Comment by aburrell** [comment]
No, the function of AACGMV2 to convert between magnetic and geodetic or geographic coordinates using  Version 2 of the Altitude-Adjusted Corrected Geomagnetic Coordinates, as stated in the documentation: https://aacgmv2.readthedocs.io/en/latest/readme.html

**Comment by hlmxlj2018** [comment]
Is the function of AACGM similar to converting the geographic coordinate information of a point of the satellite into the AACGM coordinate information of the current position. The satellite coordinate information cannot be tracked along the geomagnetic line to a plane at a low altitude

**Comment by aburrell** [comment]
@hlmxlj2018 I don't really understand what you're asking.  All AACGMV2 does is convert between geographic/geodetic and magnetic coordinates.  If you know where your satellite is, then you can get its location in magnetic coordinates.  If you don't know where it is (in latitude, longitude, and altitude), then AACGMV2 isn't going to help.

**Comment by hlmxlj2018** [comment]
After inputting the current geographic location (latitude, longitude and altitude) of the satellite into the program, the output result is actually only to convert the geographic coordinates into geomagnetic coordinates.
Is my current understanding correct?
I originally thought that the AACGM module could project the 840km satellite position along the magnetic field line to other heights, such as 110km

**Comment by aburrell** [comment]
That may be possible, but is not a use case I have encountered.  It would require a careful reading of the papers to make sure you're going about it correctly.  If possible, it would be a multi-step process along the lines of:
1) Find geomagnetic coordinates at current location
2) Extract geomagnetic elements that remain the same for tracing
3) Use those in the call at the desired altitude.
