### ISSUE TITLE
Environment variables error in Windows

### ISSUE THREAD

**Issue by gregstarr** [aburrell/aacgmv2#71]
**Describe the bug**
`aacgmv2` appears to install normally with pip. Python crashes during `c_aacgmv2.set_datetime`(https://github.com/aburrell/aacgmv2/blob/main/aacgmv2/wrapper.py#L226). The problem is that in `__init__.py`, the newly set environment variables aren't being seen by the backend C code. This causes the C code to crash during the call to `getenv`(https://github.com/aburrell/aacgmv2/blob/main/c_aacgmv2/src/aacgmlib_v2.c#L880). 

Here is what I see:
![image](https://user-images.githubusercontent.com/6515693/123905814-07afde80-d941-11eb-959a-281191844dcc.png)

When I manually set the two environment variables before starting powershell / pycharm, it works fine, but I do get the warning that the variables are being overwritten.

**To Reproduce**
1. `pip install aacgmv2`
2. run the pictured code, or the code in the README
3. Python should crash

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.7.10
 - anaconda environment
 - compiling with gcc 10.3.0 (MSYS2)

**Additional context**
- not an urgent fix: easy workaround

**Comment by aburrell** [comment]
Thanks!  I will first check and see if I can reproduce this on my mac.  That should help us see if it's OS specific or due to a change in the way the environment variables are set or accessed.

**Comment by aburrell** [comment]
Ok, can verify that I cannot reproduce this bug in OS X Sierra, python 3.7.9.  I will poke around the internet and see if I can see why the environment variables aren't being set in your version of windows.  It is working on AppVeyor with Visual Studio 2019.

**Comment by aburrell** [comment]
Quick question, what happens if you try each of these (in order)?

```
import aacgmv2
import os

os.getenv('IGRF_COEFFS')
```

If it's unknown on the system, it should return None.

```
os.environ['IGRF_COEFFS'] = 'desired path'
os.environ['AACGM_v2_DAT_PREFIX'] = 'desired path here'

print(os.getenv('IGRF_COEFFS'), os.getenv('AACGM_v2_DAT_PREFIX'))
```

If that works, what happens if you try that before importing aacgmv2 and then try your test code?  It would basically be doing what init does manually.  I am wondering if it's a problem with the `os` module interface.  The docs claim it should work on Windows, so I am curious to see what your system does.

**Comment by gregstarr** [comment]
Side note: probably unrelated, in order to get it to compile I had to replace `msvcr140` in `anaconda3\envs\aacgm\Lib\distutils\cygwinccompiler.py` with `vcruntime140`

**Comment by gregstarr** [comment]
![image](https://user-images.githubusercontent.com/6515693/125844229-e224a19c-581d-4a6d-8647-eb8201ea271c.png)

**Comment by aburrell** [comment]
Huh.  This is very confusing.  I agree that the compilation steps you made shouldn't be an issue.  Short term we can put a note in the docs about this being a potential issue and how to solve it.  I will try to think of another way to track down what's going on with the environment variables.

**Comment by hlmxlj2018** [comment]
Pycharm cannot be installed aacgmv2.At the same time, PIP cannot be installed.
