### ISSUE TITLE
RuntimeError when using the package

### ISSUE THREAD

**Issue by JouleCai** [aburrell/aacgmv2#73]
**Describe the bug**
A RuntimeError can be raised when calling the package in PyCharm or VS code.

**To Reproduce**
The package usually works fine in Spyder. However, when I compile my codes in PyCharm or VS Code, a RuntimeError is sometimes raised due to the function " c_aacgmv2.set_datetime" in aacgmv2.wrapper.convert_latlon_arr cannot set the datetime.

This error does not always appear. Sometimes, I compile the codes in Spyder several times in advance. After that, my codes work fine in Pycharm and VS Code.

I'm not sure this issue is due to the aacgmv2 package or the IDEs.

**Screenshots or Figures**

> File "/home/lcai/.conda/envs/geospacelab/lib/python3.8/site->packages/geospacelab/cs/_geo.py", line 396, in to_AACGM
>   lat[ind_dt], lon[ind_dt], r[ind_dt] = aacgm.convert_latlon_arr(in_lat=self.coords.lat[ind_dt],
> File "/home/lcai/.conda/envs/geospacelab/lib/python3.8/site-packages/aacgmv2/wrapper.py", line 367, in convert_latlon_arr
> raise RuntimeError("cannot set time for {:}: {:}".format(dtime, err))
> RuntimeError: cannot set time for 2020-12-09 13:05:42.503096: AACGM_v2_SetDateTime returned error code -2

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
- Anaconda + Python 3.8 or 3.9

**Comment by JouleCai** [comment]
The error usually occurs when I or other users run my package (https://github.com/JouleCai/geospacelab) initially using either PyCharm or VS Code. Actually, after I switch to Spyder and run the codes several times, the problem sometimes is solved. As you suggested, maybe Spyder compiles the C code correctly, and Pycharm/VS code follows the executables. 
I have added a notice regarding this issue. Spyder seems a better IDE to compile the aacgmv2 package. Thank you for your comments.

**Comment by JouleCai** [comment]
Hi,

Please let me describe the issue again: a runtime error would be returned from the function AACGM_v2_SetDateTime in the c library in ``aacgmv2``, when ``aacgmv2`` is called from another package imported in the current package rather than from the current package itself.  The issue might be associated with ``cython``, which should be installed before the installation of ``aacgmv2``.  See also the discussion JouleCai/geospacelab#6.

**Comment by aburrell** [comment]
@JouleCai I wonder if the problem has been solved now that I fixed a memory leak in the `aacgm.convert_latlon_arr` function.  If you use the current develop branch can you make the problem appear?

**Comment by JouleCai** [comment]
Thanks! I tested with the aacgmv2 v2.6.2 on Ubuntu and MacOS. No errors were found. I will close this issue.
