### ISSUE TITLE
aacgmv2.convert_latlon_arr causes a memory leak

### ISSUE THREAD

**Issue by dinsmoro** [aburrell/aacgmv2#74]
**Describe the bug**
aacgmv2.convert_latlon_arr causes a memory leak in the Python instance it is run in. For an array of 6000 points the memory leak seems to be 0.5 MB to 0.6 MB in size for each run. aacgmv2.convert_latlon (when run with the appropriate for loop to support it) does not seem to have the same memory leak issue.

`gc.collect()` cannot reclaim the memory. Killing the Python instance will reclaim the memory.

No experience with Python calling C so I can't offer any help, sadly.

**To Reproduce**
```
import numpy as np
import datetime
import aacgmv2

rando_lat = np.random.uniform(low=-90,high=90,size=6000);
rando_long = np.random.uniform(low=-180,high=180,size=6000);
for i in range(0,1000): #memory will fill up about ~500 MB from running aacgmv2.convert_latlon_arr over and over again
    _, _, _= aacgmv2.convert_latlon_arr(rando_lat, rando_long, 350., datetime.datetime(2015,5,5), method_code='G2A');
#END FOR i

for i in range(0,1000): #this one will not fill up memory
    for j in range(0,6000):
        _, _, _= aacgmv2.convert_latlon(rando_lat[j], rando_long[j], 350., datetime.datetime(2015,5,5), method_code='G2A');
    #END FOR j
#END FOR i
```

**Expected behavior**
No memory leak on aacgmv2.convert_latlon_arr

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Version Latest pip release (2.6.2)
 - Calling from Spyder

**Comment by aburrell** [comment]
I will look into this, it would be better to have this run efficiently.  Thank you for your report!

**Comment by aburrell** [comment]
Ok, I figured out what was wrong using this tutorial: https://pythonextensionpatterns.readthedocs.io/en/latest/refcount.html.  I am working on a solution, but the current test case stops the memory leak and shows that `convert_latlon_arr` is over twice as fast as `convert_latlon`.  Will let you know when I have a pull request ready.
