### ISSUE TITLE
How to use aacgmv2 beyond 2025

### ISSUE THREAD

**Issue by Yas979** [aburrell/aacgmv2#87]
Dear Dr Burrell,

Please can I ask if you are able to assist to adapt aacgmv2 for dates from 2025 until 2032, as required for a project I am working on?

On my attempt to run aacgmv2 for dates in 2025, I get the following error:
    raise RuntimeError("cannot set time for {:}: {:}".format(dtime, err))
RuntimeError: cannot set time for 2025-01-01 00:00:00+00:00: AACGM_v2_SetDateTime returned error code -1

I understand that the AACCM-v2 coefficients have been generated until 2025 and that the above error results from line 1082 in the C-library aacgmlib_v2.c:

 if ((fyear < IGRF_FIRST_EPOCH) || (fyear >= IGRF_LAST_EPOCH + 5.)) {
    AACGM_v2_errmsg(1);
    return (-1);
  }

I am assuming that the variable IGRF_LAST_EPOCH must equate to the start of 2020, however I am unable to find where IGRF_LAST_EPOCH is defined or inputted in the C Library.

Please can I ask on how I can adapt the current code or coefficient data files to enable aacgmv2 from 2025 until 2032?

Kind regards,
Yasir

**Comment by aburrell** [comment]
Hi @Yas979, we won't be able to go further in the future until a new version of the IGRF coefficients are released.  In the meantime, I'd recommend just using the latest available year.

**Comment by Yas979** [comment]
Hi @aburrell, thanks so much for the quick reply.

**Comment by Yas979** [comment]
Hi @aburrell,

I have attempted to extend files the different .txt files in the aacgmv2 folders to include years up to 2035 and likewise made extra copies of the coefficient files. However, I'm still unable to run aacgmv2 for dates further than 2025.

I realise the module _aacgmv2.set_datetime must set the maximum date allowed and was hoping to see how this time is set and if there is a certain input I could change somewhere or if it is hardcoded. However, as I am unable to open _aacgmv2.cpython-36m-x186_64-linux-gnu.so I am not able to proceed any further. 

Please can I ask if you are aware of how the maximum date of 2025 is set within the aacgmv2 and if there is anyway to change this?

Thanks,
Yasir

**Comment by aburrell** [comment]
This is defined in the C code, so not something I'd recommend changing.  The best thing to do would be to just not increment your time (set the max date and don't cycle it further in your processing).

**Comment by Yas979** [comment]
Thanks @aburrell. Yep, for now I reset all years equal to or above 2025 to 2024 and hope this will do. Best, Yasir
